-- Add ICD-10 Sample Data for Ministry Compliance
INSERT INTO public.icd10_codes (code, description, category, subcategory) VALUES
('A00', 'Cholera', 'Infectious and parasitic diseases', 'Intestinal infectious diseases'),
('A01', 'Typhoid and paratyphoid fevers', 'Infectious and parasitic diseases', 'Intestinal infectious diseases'),
('A02', 'Other salmonella infections', 'Infectious and parasitic diseases', 'Intestinal infectious diseases'),
('A03', 'Shigellosis', 'Infectious and parasitic diseases', 'Intestinal infectious diseases'),
('A04', 'Other bacterial intestinal infections', 'Infectious and parasitic diseases', 'Intestinal infectious diseases'),
('A05', 'Other bacterial foodborne intoxications', 'Infectious and parasitic diseases', 'Intestinal infectious diseases'),
('A06', 'Amebiasis', 'Infectious and parasitic diseases', 'Intestinal infectious diseases'),
('A07', 'Other protozoal intestinal diseases', 'Infectious and parasitic diseases', 'Intestinal infectious diseases'),
('A08', 'Viral and other specified intestinal infections', 'Infectious and parasitic diseases', 'Intestinal infectious diseases'),
('A09', 'Diarrhea and gastroenteritis of presumed infectious origin', 'Infectious and parasitic diseases', 'Intestinal infectious diseases'),
('B50', 'Plasmodium falciparum malaria', 'Infectious and parasitic diseases', 'Protozoal diseases'),
('B51', 'Plasmodium vivax malaria', 'Infectious and parasitic diseases', 'Protozoal diseases'),
('B52', 'Plasmodium malariae malaria', 'Infectious and parasitic diseases', 'Protozoal diseases'),
('B53', 'Other specified malaria', 'Infectious and parasitic diseases', 'Protozoal diseases'),
('B54', 'Unspecified malaria', 'Infectious and parasitic diseases', 'Protozoal diseases'),
('B20', 'Human immunodeficiency virus [HIV] disease', 'Infectious and parasitic diseases', 'Viral diseases'),
('A15', 'Respiratory tuberculosis', 'Infectious and parasitic diseases', 'Tuberculosis'),
('A16', 'Respiratory tuberculosis, not confirmed bacteriologically or histologically', 'Infectious and parasitic diseases', 'Tuberculosis'),
('A17', 'Tuberculosis of nervous system', 'Infectious and parasitic diseases', 'Tuberculosis'),
('A18', 'Tuberculosis of other organs', 'Infectious and parasitic diseases', 'Tuberculosis'),
('A19', 'Miliary tuberculosis', 'Infectious and parasitic diseases', 'Tuberculosis'),
('E10', 'Type 1 diabetes mellitus', 'Endocrine, nutritional and metabolic diseases', 'Diabetes mellitus'),
('E11', 'Type 2 diabetes mellitus', 'Endocrine, nutritional and metabolic diseases', 'Diabetes mellitus'),
('E12', 'Malnutrition-related diabetes mellitus', 'Endocrine, nutritional and metabolic diseases', 'Diabetes mellitus'),
('E13', 'Other specified diabetes mellitus', 'Endocrine, nutritional and metabolic diseases', 'Diabetes mellitus'),
('E14', 'Unspecified diabetes mellitus', 'Endocrine, nutritional and metabolic diseases', 'Diabetes mellitus'),
('I10', 'Essential hypertension', 'Diseases of the circulatory system', 'Diseases of arteries, arterioles and capillaries'),
('I11', 'Hypertensive heart disease', 'Diseases of the circulatory system', 'Diseases of arteries, arterioles and capillaries'),
('I12', 'Hypertensive chronic kidney disease', 'Diseases of the circulatory system', 'Diseases of arteries, arterioles and capillaries'),
('I13', 'Hypertensive heart and chronic kidney disease', 'Diseases of the circulatory system', 'Diseases of arteries, arterioles and capillaries'),
('I15', 'Secondary hypertension', 'Diseases of the circulatory system', 'Diseases of arteries, arterioles and capillaries'),
('J12', 'Viral pneumonia', 'Diseases of the respiratory system', 'Influenza and pneumonia'),
('J13', 'Pneumonia due to Streptococcus pneumoniae', 'Diseases of the respiratory system', 'Influenza and pneumonia'),
('J14', 'Pneumonia due to Hemophilus influenzae', 'Diseases of the respiratory system', 'Influenza and pneumonia'),
('J15', 'Bacterial pneumonia, not elsewhere classified', 'Diseases of the respiratory system', 'Influenza and pneumonia'),
('J16', 'Pneumonia due to other infectious organisms, not elsewhere classified', 'Diseases of the respiratory system', 'Influenza and pneumonia'),
('J18', 'Pneumonia, organism unspecified', 'Diseases of the respiratory system', 'Influenza and pneumonia'),
('K25', 'Gastric ulcer', 'Diseases of the digestive system', 'Diseases of oesophagus, stomach and duodenum'),
('K26', 'Duodenal ulcer', 'Diseases of the digestive system', 'Diseases of oesophagus, stomach and duodenum'),
('K27', 'Peptic ulcer, site unspecified', 'Diseases of the digestive system', 'Diseases of oesophagus, stomach and duodenum'),
('K28', 'Gastrojejunal ulcer', 'Diseases of the digestive system', 'Diseases of oesophagus, stomach and duodenum'),
('K29', 'Gastritis and duodenitis', 'Diseases of the digestive system', 'Diseases of oesophagus, stomach and duodenum'),
('C50', 'Malignant neoplasm of breast', 'Neoplasms', 'Malignant neoplasms'),
('C78', 'Secondary malignant neoplasm of respiratory and digestive organs', 'Neoplasms', 'Malignant neoplasms'),
('C79', 'Secondary malignant neoplasm of other and unspecified sites', 'Neoplasms', 'Malignant neoplasms'),
('C80', 'Malignant neoplasm without specification of site', 'Neoplasms', 'Malignant neoplasms'),
('C81', 'Hodgkin lymphoma', 'Neoplasms', 'Malignant neoplasms'),
('C82', 'Follicular lymphoma', 'Neoplasms', 'Malignant neoplasms'),
('C83', 'Non-follicular lymphoma', 'Neoplasms', 'Malignant neoplasms'),
('C84', 'Mature T/NK-cell lymphomas', 'Neoplasms', 'Malignant neoplasms'),
('C85', 'Other and unspecified types of non-Hodgkin lymphoma', 'Neoplasms', 'Malignant neoplasms'),
('C88', 'Malignant immunoproliferative diseases and certain other B-cell lymphomas', 'Neoplasms', 'Malignant neoplasms'),
('C90', 'Multiple myeloma and malignant plasma cell neoplasms', 'Neoplasms', 'Malignant neoplasms'),
('C91', 'Lymphoid leukemia', 'Neoplasms', 'Malignant neoplasms'),
('C92', 'Myeloid leukemia', 'Neoplasms', 'Malignant neoplasms'),
('C93', 'Monocytic leukemia', 'Neoplasms', 'Malignant neoplasms'),
('C94', 'Other leukemias of specified cell type', 'Neoplasms', 'Malignant neoplasms'),
('C95', 'Leukemia of unspecified cell type', 'Neoplasms', 'Malignant neoplasms'),
('C96', 'Other and unspecified malignant neoplasms of lymphoid, hematopoietic and related tissue', 'Neoplasms', 'Malignant neoplasms'),
('C97', 'Malignant neoplasms of independent (primary) multiple sites', 'Neoplasms', 'Malignant neoplasms')
ON CONFLICT (code) DO NOTHING;
